# Generated by Django 5.2 on 2025-04-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_uploadedimage_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideshow_speed', models.PositiveIntegerField(default=5)),
                ('upload_cooldown', models.PositiveIntegerField(default=10)),
                ('camera_cooldown', models.PositiveIntegerField(default=10)),
                ('upload_enabled', models.BooleanField(default=True)),
                ('slideshow_random', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Konfiguration',
                'verbose_name_plural': 'Konfigurationen',
            },
        ),
    ]
